name: habit_harmony
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  animations: ^2.0.7
  responsive_framework: ^1.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets section for images and icons
 # assets:
 #   - assets/icons/


  # Add fonts section for custom fonts
 # fonts:
 #   - family: Roboto
  #    fonts:
  #      - asset: fonts/Roboto-Regular.ttf
