// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgKIi5LpdPxgg3St7wiSTy48CGKCyuMs0',
    appId: '1:815879238665:web:00371854fb21027301b4d8',
    messagingSenderId: '815879238665',
    projectId: 'habit-harmony-a86e9',
    authDomain: 'habit-harmony-a86e9.firebaseapp.com',
    storageBucket: 'habit-harmony-a86e9.appspot.com',
    measurementId: 'G-HYMHB8G1CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EO-7sAjo1HCxfkNwpvVipi9eDPGhU3Q',
    appId: '1:815879238665:android:ae8b7e07389b069101b4d8',
    messagingSenderId: '815879238665',
    projectId: 'habit-harmony-a86e9',
    storageBucket: 'habit-harmony-a86e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLk_6ggbon648AoEECJbJSaN3cIQf-94',
    appId: '1:815879238665:ios:4cec2611e326a5de01b4d8',
    messagingSenderId: '815879238665',
    projectId: 'habit-harmony-a86e9',
    storageBucket: 'habit-harmony-a86e9.appspot.com',
    iosBundleId: 'com.example.habitHarmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLk_6ggbon648AoEECJbJSaN3cIQf-94',
    appId: '1:815879238665:ios:4cec2611e326a5de01b4d8',
    messagingSenderId: '815879238665',
    projectId: 'habit-harmony-a86e9',
    storageBucket: 'habit-harmony-a86e9.appspot.com',
    iosBundleId: 'com.example.habitHarmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgKIi5LpdPxgg3St7wiSTy48CGKCyuMs0',
    appId: '1:815879238665:web:30450df481b6270b01b4d8',
    messagingSenderId: '815879238665',
    projectId: 'habit-harmony-a86e9',
    authDomain: 'habit-harmony-a86e9.firebaseapp.com',
    storageBucket: 'habit-harmony-a86e9.appspot.com',
    measurementId: 'G-HFKCLJTNSK',
  );
}
